### ISSUE TITLE
Installing via HA Add-On > Repositories page errors

### ISSUE THREAD

**Issue by JohnMcLear** [erik73/addon-mail#194]
# Problem/Motivation

I'm trying to test the Add-on but installation fails as 
``https://github.com/erik73/addon-mail is not a valid add-on repository``

## Expected behavior

Add on will install

## Actual behavior

Add on does not  install

## Steps to reproduce

Click Add-Ons > Add on store > Repositories > enter URL for repo ``https://github.com/erik73/addon-mail/`` and click Add

## Proposed changes

No suggestion to fix.

**Comment by erik73** [comment]
The repository is: https://github.com/erik73/hassio-addons
