### ISSUE TITLE
Access emails from Home Assistant

### ISSUE THREAD

**Issue by ElVit** [erik73/addon-mail#270]
# Problem/Motivation

> Is it possible to access the emails from home assistant?
> It would be nice to see each email as a file and open them in a text editor.
> As far as I know the email file format should be mbox right?

## Expected behavior

> 

## Actual behavior

> It is probably only possible to access the email files by using portainer.
> But I dont know where they are located...

## Steps to reproduce

>

## Proposed changes

> Maybe its possible to show the directory containing the emails somewhere in /share directory or the new /addon_configs directory.

**Comment by ElVit** [comment]
And I think its also not possible to see the emails in the PostfixAdmin UI right?
So in general it would be great if I could see my emails (and its content) in Home Assistant.

**Comment by erik73** [comment]
Perhaps a stupid question, but can you not solve that in your email client software?
Are you running HomeAssistant Operating System or HomeAssistant supervised?

**Comment by erik73** [comment]
BTW
You can find your emails in the mail server container at: /var/mail/vmail/<your.domain.com>/<your.username>

**Comment by ElVit** [comment]
Sorry for my late reply. 
Thanks for the path where I can find the email files. 
Currently I have not exposed the mail server addon to the internet so i can only access it at home. 
I use the addon simply for archiving my emails. So i don't need to send any emails but want only to see them.

**Comment by erik73** [comment]
Ok, I understand. 
The simple answer is that it is not possible to view the contents your mailbox in the UI.
You have to use come kind of email client software to do that.
