### ISSUE TITLE
exited 127

### ISSUE THREAD

**Issue by AvocadoPanic** [erik73/addon-mail#273]
Unable to login following install. Postfixadmin db appears to be empty. 

Unexpected error in install log:

/var/www/postfixadmin/scripts/postfixadmin-cli: line 34: exec: php: not found
cont-init: info: /etc/cont-init.d/10-create-config.sh exited 127
cont-init: warning: some scripts exited nonzero
s6-rc: warning: unable to start service legacy-cont-init: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.

**Comment by erik73** [comment]
Strange. What version of the add-on are you using? And, what hardware platform?

**Comment by AvocadoPanic** [comment]
I've version 2.0.2

It's a generic x86 (Gigabyte)

I'm using Homeassistant OS on bare metal.

Core
2023.12.4
Supervisor
2023.12.0
Operating System
11.2
Frontend
20231208.2

**Comment by erik73** [comment]
Thanks for finding this!

I was able to replicate the error, and fixed the problem in version 2.0.3.

If it works for you, please close this issue.
