### ISSUE TITLE
Admin password

### ISSUE THREAD

**Issue by fredericobatista** [erik73/addon-mail#274]
whats the default password to access or file configuration to setup?
Try a lot times configure admin_user and admin_passord and not work

**Comment by erik73** [comment]
Have you seen this in the documentation:Please note: During the startup of the add-on, a database is created in the MariaDB add-on. There is currently not possible to change user credentials or domain_name after the database is created. The only way to change these options is to drop the Postfix Admin datbase and restart the add-on. Use the phpMyadmin add-on to drop the database.And this:To log in to the web interface you have to use FQDN. For ***@***.*** In the current version of the add-on, this can not be changed once the database is created.Skickat från min iPhone31 dec. 2023 kl. 20:08 skrev fredericobatista ***@***.***>:﻿
whats the default password to access or file configuration to setup?
Try a lot times configure admin_user and admin_passord and not work
