### ISSUE TITLE
Custom config files?

### ISSUE THREAD

**Issue by Smart-24-7** [erik73/addon-mail#277]
Is it possible, as an end user, to add my own entries to some files under /etc/postfix, especially main.cf, canonical and virtual?

I'm not very experienced with Docker, but I assume changes are lost with every restart. Can persistent changes be made via the GUI or via the command line?

**Comment by erik73** [comment]
Hi. 

You are correct. Changes made inside the container will be lost at reboot. 
The only way to change the configuration files is by making them as options in the add-on config. 
That means that I have to expose new configuration options and publish a new version of the add-on. 

Please describe your use case, and what you want to have as config options and I will see if I can implement them. 
no promises, but if it will benefit others I think it is worth looking at.

**Comment by Smart-24-7** [comment]
Thank you for the fast response. Give me a few days to describe it so that it is understandable.
