### ISSUE TITLE
Wrappermode

### ISSUE THREAD

**Issue by ScanEarth** [erik73/addon-mail#312]
# Problem/Motivation

I'm getting this error:
2024-09-10 13:18:46.685309102  mail.info: Sep 10 13:18:46 postfix/smtp[417]: SMTPS wrappermode (TCP port 465) requires setting "smtp_tls_wrappermode = yes", and "smtp_tls_security_level = encrypt" (or stronger)

## Expected behavior

Auth to smtp_relayhost

## Actual behavior

Rejected

## Proposed changes

See if this can be added or if config switch is needed to turn on or off.

**Comment by erik73** [comment]
Sorry, I have had limited time to work on this project. 
I will have to create a new config options for this use case, if you are willing to test.

**Comment by ScanEarth** [comment]
Hi I got it to work but I’m not sure if this is the most secure way. I have to go through my ISPs outbound SMTP to get mail outbound…_________________________________________________Filippe Åhlund 070-393 11 63 3 okt. 2024 kl. 09:40 skrev Erik Hilton ***@***.***>:﻿
Sorry, I have had limited time to work on this project.
I will have to create a new config options for this use case, if you are willing to test.
