### ISSUE TITLE
ERROR: Got unexpected response from the API: Service not enabled

### ISSUE THREAD

**Issue by jeanbart82** [erik73/addon-mail#73]
Hi!

Don't know what I am doing wrong, but seems it need some API service?

see log below... what should I do?

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Mailserver
 Postfix and Dovecot mail server for Home Assistant, with Postfix Admin web interface
-----------------------------------------------------------
 Add-on version: 1.2.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 5.13  (aarch64 / odroid-n2)
 Home Assistant Core: 2021.4.6
 Home Assistant Supervisor: 2021.04.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 10-create-config.sh: executing... 
[20:28:04] ERROR: Got unexpected response from the API: Service not enabled
[20:28:05] INFO: Let's Encrypt certs will be used...
[cont-init.d] 10-create-config.sh: exited 139.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

**Comment by erik73** [comment]
Have you installed the official MariaDB add-on?
It is needed to store the postfix database.
