### ISSUE TITLE
Getting a postmaster failure when sending email

### ISSUE THREAD

**Issue by tonysprenk** [erik73/addon-mail#95]
Starting today I am not able to send emails. Every time I try I get an instant email back saying that my ip address has been listed at SpamHaus. This never used to happen. I have duckdns setup so my io address shouldn’t be used anyway. What am I doing wrong?

**Comment by erik73** [comment]
Sorry, but this is a little bit out of scope for the add-on itself. 
It is a complex task to host your own mail server, and the problem you are facing is probably more related to the setup you have outside of the add-on. For example using a dynamic public IP-address without control over PTR records etc.

Tell me a little bit about of your setup with regards to DNS, relay servers etc. Perhaps I can point you in the right direction…

**Comment by tonysprenk** [comment]
I fixed it, something was wrong with my smtp relay. Sorry for the trouble.
